INSERT INTO categories (name) VALUES ('Electronics');
INSERT INTO categories (name) VALUES ('Office Supplies');
INSERT INTO categories (name) VALUES ('Furniture');

INSERT INTO suppliers (name, contact_info, foundation_year, sector) VALUES ('Tech Supplier Inc.', 'techsupplier@example.com', 2001, 0);
INSERT INTO suppliers (name, contact_info, foundation_year, sector) VALUES ('Office Supplies Co.', 'officesupplies@example.com', 1995, 1);
INSERT INTO suppliers (name, contact_info, foundation_year, sector) VALUES ('Home Furniture Ltd.', 'homefurniture@example.com', 1980, 2);

INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Smartphone X', 11345.99, '2023-01-15', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Laptop Pro', 15678.49, '2023-02-20', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Wireless Headphones', 2450.29, '2022-03-10', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Gaming Mouse', 58.99, '2020-04-05', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Tablet Elite', 6612.79, '2023-05-12', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Smartwatch Sport', 517.99, '2021-06-18', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Home Security Camera', 22.49, '2022-07-22', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Wireless Keyboard', 129.99, '2024-08-30', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Bluetooth Speaker', 214.29, '2018-09-14', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Smart TV S10', 8914.29, '2019-09-14', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 1);

INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Desk Organizer', 327.99, '2022-11-08', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Printer Paper (500 sheets)', 125.49, '2022-12-15', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Stapler', 4.99, '2023-01-20', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Desktop Organizer', 97.29, '2023-02-25', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Whiteboard Markers (Pack of 12)', 226.99, '2023-03-12', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Desk Lamp', 155.99, '2023-04-18', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Document Organizer', 110.49, '2023-05-25', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('File Folders (Pack of 50)', 118.99, '2023-06-30', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Wireless Mouse', 87.99, '2023-08-20', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Bulletin Board', 20.49, '2023-09-25', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 2);

INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Leather Sofa', 699.99, '2023-01-05', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Dining Table', 299.99, '2023-02-10', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Office Chair', 129.99, '2023-03-15', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('King Size Bed', 899.99, '2023-04-20', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Coffee Table', 149.99, '2023-05-25', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Wooden Wardrobe', 799.99, '2023-06-30', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Bedroom Dresser', 199.99, '2023-07-05', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Leather Armchair', 399.99, '2023-08-10', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Side Table', 79.99, '2023-10-20', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);
INSERT INTO products (name, price, manufacture_date, rating, description, supplier_id) VALUES ('Corner Desk', 149.99, '2023-11-25', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut arcu at turpis ullamcorper luctus eget non ex. Maecenas at purus sollicitudin, malesuada ligula ut, lacinia justo. Aliquam non libero massa. Integer mollis congue viverra. Nullam pellentesque, leo ut malesuada euismod, tortor dolor convallis lorem, vitae efficitur elit lorem ac lectus. Aliquam nec erat nec elit laoreet suscipit ac in urna. Proin a laoreet lorem.', 3);

INSERT INTO product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO product_category (product_id, category_id) VALUES (10, 1);

INSERT INTO product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO product_category (product_id, category_id) VALUES (13, 2);
INSERT INTO product_category (product_id, category_id) VALUES (14, 2);
INSERT INTO product_category (product_id, category_id) VALUES (15, 2);
INSERT INTO product_category (product_id, category_id) VALUES (16, 2);
INSERT INTO product_category (product_id, category_id) VALUES (17, 2);
INSERT INTO product_category (product_id, category_id) VALUES (18, 2);
INSERT INTO product_category (product_id, category_id) VALUES (19, 2);
INSERT INTO product_category (product_id, category_id) VALUES (20, 2);

INSERT INTO product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO product_category (product_id, category_id) VALUES (25, 3);
INSERT INTO product_category (product_id, category_id) VALUES (26, 3);
INSERT INTO product_category (product_id, category_id) VALUES (27, 3);
INSERT INTO product_category (product_id, category_id) VALUES (28, 3);
INSERT INTO product_category (product_id, category_id) VALUES (29, 3);
INSERT INTO product_category (product_id, category_id) VALUES (30, 3);

INSERT INTO users (name, email, password) VALUES ('Cauê Garcia', 'caue@outlook.com', 'app-2024');
INSERT INTO users (name, email, password) VALUES ('Geilson Freire', 'geilson@outlook.com', 'app-2024');
INSERT INTO users (name, email, password) VALUES ('Junior Ciqueira', 'junior@gmail.com', 'app-2024');
INSERT INTO users (name, email, password) VALUES ('Everton Freire', 'everton@gmail.com', 'app-2024');

INSERT INTO roles (authority) VALUES ('ROLE_CLIENT');
INSERT INTO roles (authority) VALUES ('ROLE_STOCK_MANAGER');

INSERT INTO user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO user_role (user_id, role_id) VALUES (4, 1);

